after-login-command = []
after-startup-command = [
  'exec-and-forget defaults write -g NSAutomaticWindowAnimationsEnabled -bool false',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       12
outer.bottom =     15
outer.top =        10
outer.right =      12

[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/usr/local/bin:${PATH}'

[mode.main.binding]
cmd-enter = 'exec-and-forget alacritty msg create-window -e /usr/local/bin/zellij attach -c default || alacritty -e /usr/local/bin/zellij attach -c default'
cmd-h = []
ctrl-alt-d = 'fullscreen'
ctrl-alt-space = 'layout horizontal vertical'

ctrl-alt-h = 'focus left'
ctrl-alt-j = 'focus down'
ctrl-alt-k = 'focus up'
ctrl-alt-l = 'focus right'

# ctrl-alt-h = 'join-with left'
# ctrl-alt-j = 'join-with down'
# ctrl-alt-k = 'join-with up'
# ctrl-alt-l = 'join-with right'

ctrl-cmd-minus = 'resize smart -50'
ctrl-cmd-equal = 'resize smart +50'

cmd-1 = 'workspace term'
cmd-2 = 'workspace web'
cmd-3 = 'workspace chat'
cmd-4 = 'workspace cal'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'

ctrl-alt-1 = 'move-node-to-workspace term'
ctrl-alt-2 = 'move-node-to-workspace web'
ctrl-alt-3 = 'move-node-to-workspace chat'
ctrl-alt-4 = 'move-node-to-workspace cal'
ctrl-alt-5 = 'move-node-to-workspace 5'
ctrl-alt-6 = 'move-node-to-workspace 6'
ctrl-alt-7 = 'move-node-to-workspace 7'
ctrl-alt-8 = 'move-node-to-workspace 8'
ctrl-alt-9 = 'move-node-to-workspace 9'

ctrl-alt-semicolon = 'mode service'

[mode.service.binding]
r = ['reload-config', 'mode main']
w = ['close-all-windows-but-current', 'mode main']
