after-login-command = []
after-startup-command = [
  'exec-and-forget defaults write -g NSAutomaticWindowAnimationsEnabled -bool false',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       12
outer.bottom =     15
outer.top =        10
outer.right =      12

[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
cmd-enter = 'exec-and-forget /Applications/Alacritty.app/Contents/MacOS/alacritty'
cmd-h = []
alt-shift-d = 'fullscreen'
alt-shift-space = 'layout horizontal vertical'

alt-shift-h = 'focus left'
alt-shift-j = 'focus down'
alt-shift-k = 'focus up'
alt-shift-l = 'focus right'

alt-h = 'join-with left'
alt-j = 'join-with down'
alt-k = 'join-with up'
alt-l = 'join-with right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

cmd-1 = 'workspace term'
cmd-2 = 'workspace web'
cmd-3 = 'workspace chat'
cmd-4 = 'workspace cal'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace term'
alt-shift-2 = 'move-node-to-workspace web'
alt-shift-3 = 'move-node-to-workspace chat'
alt-shift-4 = 'move-node-to-workspace cal'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
r = ['reload-config', 'mode main']
w = ['close-all-windows-but-current', 'mode main']
