#!/usr/bin/env bash

# System
alias shutdown='sudo shutdown now'
alias reboot='sudo reboot'
alias suspend='sudo pm-suspend'

# Filesystem
alias cd='z'

# zsh
alias zenv='vim ${DOTFILES}/.zshenv'
alias zalias='vim ${ZDOTDIR}/aliases'
alias zconfig='vim ${ZDOTDIR}/.zshrc'
alias zsource='source ${ZDOTDIR}/.zshrc'

# CLIs
alias hg='history | grep'

alias ls='eza --color=always --group-directories-first'
alias ll='eza -la --color=always --group-directories-first'

# Git
alias gitclean='git branch --merged| grep -Ev "(^\*|master|main|dev)"'
