import = [
  # "~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml",
  "~/.config/alacritty/themes/rose-pine/rose-pine.toml",
  "~/.config/alacritty/fonts.toml"
]
live_config_reload = true

[cursor]
##unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
decorations = "buttonless"
# decorations = "full"
# decorations = "Transparent"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 0.85
startup_mode = "Windowed"

[window.dimensions]
columns = 400
lines = 200

[window.padding]
x = 20
y = 20
