import = [
  "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml",
  "~/.config/alacritty/fonts.toml"
]

live_config_reload = true

[shell]
program = "zellij"
args = ["attach", "-c", "default"]

[cursor.style]
blinking = "On"
shape = "Block"

[[keyboard.bindings]]
 chars = "\u001BF"
 key = "l"
 mods = "Alt"

[[keyboard.bindings]]
 chars = "\u001BB"
 key = "h"
 mods = "Alt"

[window]
decorations = "buttonless"
dynamic_title = true
# history = 10000
startup_mode = "Windowed"
option_as_alt = "Both"

[window.dimensions]
columns = 400
lines = 200

[window.padding]
x = 10
y = 10
