import = [
  "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml",
  "~/.config/alacritty/fonts.toml"
]
live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
 chars = "\u001BF"
 key = "Right"
 mods = "Alt"

[[keyboard.bindings]]
 chars = "\u001BB"
 key = "Left"
 mods = "Alt"

[window]
decorations = "buttonless"
# decorations = "full"
# decorations = "Transparent"
dynamic_title = true
# history = 10000
# multiplier = 3
# opacity = 0.9
startup_mode = "Windowed"
option_as_alt = "Both"

[window.dimensions]
columns = 400
lines = 200

[window.padding]
x = 10
y = 10
